# Change these first
owner: roswellit # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Microsoft 365 - Outlook for Web
    url: https://outlook.office365.com
  - name: Microsoft 365 - Exchange Online Message Delivery
    check: "tcp-ping"
    url: roswellit-com.mail.protection.outlook.com
    port: 25
  - name: Our Website - roswellit.com
    url: https://roswellit.com
  - name: Customer Remote Monitoring & Management Services
    url: https://roswellitservices.hostedrmm.com
  - name: Customer Helpdesk
    url: https://roswell.myportallogin.co.uk
  - name: Roswell IT connectwise server
    url: https://roswellitservices.hostedrmm.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.roswellit.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Roswell Status
  introTitle: "Welcome"
  introMessage: "Here you can see the status of popular and public hosted services, products that are integrated as part of our managed services offerings, as well as any messages posted regarding incidents affecting other services you might be trying to access."
  navbar:
    - title: www.roswellit.com
      href: https://roswellit.com
    - title: support@roswellit.com
      href: mailto://support@roswellit.com
    - title: 01355 265588
      href: tel:01355265588
      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
