# Change these first
owner: roswellit # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: status.roswellit.com

sites:
  - name: www.roswellit.com
    url: https://roswellit.com
  - name: portal.roswellit.com
    url: https://roswell.myportallogin.co.uk
  - name: help.roswellit.com
    url: https://roswellitservices.hostedrmm.com:8040/
  - name: Daisy Business Broadband Services
    check: "tcp-ping"
    url: 62.232.218.2
    port: 2003
  - name: HVS - Platform
    check: "tcp-ping"
    url: dm.yourwhc.co.uk
    port: 443
  - name: HVS - Office UC
    check: "tcp-ping"
    url: officeuc.yourwhc.co.uk
    port: 443
  - name: HVS - Go TAPI Integrator
    check: "tcp-ping"
    url: applications.yourwhc.co.uk
    port: 443
  - name: Google Public Recursive DNS
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
  - name: CloudFlare Public Recursive DNS
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
  - name: Remote Monitoring & Management
    url: https://roswellitservices.hostedrmm.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.roswellit.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Roswell Status
  introTitle: "Welcome"
  introMessage: "Here you can see the status of popular and public hosted services, products that are integrated as part of our managed services offerings, as well as any messages posted regarding incidents affecting other services you might be trying to access."
  navbar:
    - title: www.roswellit.com
      href: https://roswellit.com
    - title: support@roswellit.com
      href: mailto://support@roswellit.com
    - title: 01355 265588
      href: tel:01355265588
      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
